[package]
name = "rust-ai-ide-work-stealing-scheduler"
version = "0.1.0"
edition = "2021"
rust-version = "1.91.0"

[dependencies]
tokio = { version = "1.0", features = ["full", "rt-multi-thread"] }
async-trait = "0.1"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
tracing = "0.1"
tokio-util = "0.7"
crossbeam-deque = "0.8"
parking_lot = "0.12"

[dev-dependencies]
criterion = "0.5"
tokio-test = "0.4"
