[package]
name = "rust-ai-ide-shared-utils"
readme = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
description = "Shared utilities for Rust AI IDE"
license = { workspace = true }
rust-version = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }

[dependencies]
dunce = { workspace = true }
pathdiff = "0.2.0"