[package]
name = "rust-ai-ide-performance-monitoring"
readme = { workspace = true }
version = "0.1.0"
edition = "2021"
authors = ["Rust AI IDE Team"]
license = "MIT OR Apache-2.0"
publish = false
rust-version = "1.91.0"

[dependencies]
rust-ai-ide-common = { path = "../rust-ai-ide-common" }
rust-ai-ide-errors = { path = "../rust-ai-ide-errors" }
rust-ai-ide-types = { path = "../rust-ai-ide-types" }
serde = { version = "^1.0.219", features = ["derive"] }
serde_json = "^1.0.143"
tokio = { version = "1.47.1", features = ["full"] }
chrono = { version = "0.4.42", features = ["serde"] }
sysinfo = "~0.37.0"
uuid = { version = "^1.18.1", features = ["v4"] }
moka = { version = "0.12.10", features = ["future"] }
thiserror = "2.0.16"
anyhow = "^1.0.99"
futures = "^0.3.31"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser", "powerbase"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2"
signal-hook = "0.3"

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.25"
objc = "0.2.7"