[package]
name = "rust-ai-ide-dsl-codegen"
readme = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
publish = { workspace = true }

[dependencies]
# Core dependencies
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true, features = ["full"] }

# Parsing and AST
pest = { version = "2.7" }
pest_derive = { version = "2.7" }
lalrpop = { version = "0.20" }
lalrpop-util = { version = "0.20" }
regex = { version = "1.10" }

# Shared infrastructure
rust-ai-ide-common = { path = "../rust-ai-ide-common" }
rust-ai-ide-shared-codegen = { path = "../rust-ai-ide-shared-codegen" }
rust-ai-ide-cache = { path = "../rust-ai-ide-cache" }

# LSP integration
rust-ai-ide-lsp = { path = "../rust-ai-ide-lsp" }

# AI integration (for Phase 1 patterns)
rust-ai-ide-ai = { path = "../rust-ai-ide-ai" }
rust-ai-ide-ai-analysis = { path = "../rust-ai-ide-ai-analysis" }

# Testing
[dev-dependencies]
tempfile = { workspace = true }
rstest = "0.18"

[[bin]]
name = "dsl-codegen-demo"
readme = { workspace = true }
path = "src/main.rs"