global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'rust-ai-ide'
    static_configs:
      - targets: ['127.0.0.1:9090']
    scrape_interval: 30s
    metrics_path: '/metrics'
