# cargo-deny configuration file
#
# This configuration defines policies for dependency security,
# licensing compliance, and banned packages.

[advisories]
yanked = "warn"
vulnerability = "deny"
unmaintained = "warn"
unsound = "deny"
notice = "warn"
ignore = []

[bans]
enforce-ban = true
multiple-versions = "warn"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
deny = [
    { name = "openssl", version = "*", reason = "Use rustls instead for security" },
    { name = "openssl-sys", version = "*", reason = "Use rustls instead for security" },
    { name = "native-tls", version = "*", reason = "Use rustls instead for security" },
    { name = "md5", version = "*", reason = "MD5 is cryptographically broken and insecure. Use sha2 instead" },
    { name = "ring", version = "*", reason = "Contains low-level cryptographic code that could introduce vulnerabilities" },
    { name = "quick-js", version = "*", reason = "Experimental JsEngine with known security concerns" },
    { name = "libsqlite3-sys", version = "*", reason = "Use rusqlite instead for bundled SQLite", allow-wrappers = ["rusqlite"] },
]
allow = []

[versions]
enforce = [
  { name = "rusqlite", version = "*" },
]

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "CC0-1.0",
    "0BSD",
    "Zlib",
    "BSL-1.0",
    "MPL-2.0",
    "Unlicense",
]
exceptions = [
    { allow = ["CC0-1.0"], name = "sqlite3-src", version = "*" },
    { allow = ["MPL-2.0"], name = "webpki-roots", version = "*" },
    { allow = ["GPL-2.0", "GPL-3.0", "LGPL-2.1"], name = "git2", version = "*" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
