# cargo-deny configuration file
#
# This configuration defines policies for dependency security,
# licensing compliance, and banned packages.

[advisories]
yanked = "warn"

[bans]
multiple-versions = "warn"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
deny = [
    { name = "openssl", reason = "Use rustls instead" },
    { name = "md5", reason = "MD5 is cryptographically broken" },
    { name = "ring", reason = "Contains low-level cryptographic code that could introduce vulnerabilities" },
    { name = "quick-js", reason = "Experimental JsEngine with known security concerns" },
    { name = "libsqlite3-sys", reason = "Use rusqlite instead" },
]

[versions]
enforce = [
  { name = "rusqlite", version = "*" },
]

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "CC0-1.0",
    "0BSD",
    "Zlib",
    "BSL-1.0",
    "MPL-2.0",
    "Unlicense",
]
exceptions = [
    { allow = ["CC0-1.0"], name = "sqlite3-src", version = "*" },
    { allow = ["MPL-2.0"], name = "webpki-roots", version = "*" },
    { allow = ["GPL-2.0", "GPL-3.0", "LGPL-2.1"], name = "git2", version = "*" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
