[package]
name = "rust-ai-ide-code-style"
readme = { workspace = true }
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
syn = { version = "2.0", features = ["full"] }
proc-macro2 = "1.0"
quote = "1.0"
regex = "1.10"
async-trait = "0.1"
futures = "0.3"
strsim = "0.11"
toml = "0.8"
uuid = { version = "1.0", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
tracing = "0.1"
petgraph = "0.6"

[dependencies.rust-ai-ide-core]
path = "../rust-ai-ide-core"

[dependencies.rust-ai-ide-types]
path = "../rust-ai-ide-types"

[dependencies.rust-ai-ide-ai-analysis]
path = "../rust-ai-ide-ai-analysis"