[package]
name = "rust-ai-ide-errors"
readme = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
description = "Unified error handling for Rust AI IDE"
license = { workspace = true }
rust-version = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }

[dependencies]
thiserror = { workspace = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
axum = { version = "0.8.4", optional = true }
http = { version = "1.3.1", optional = true }
chrono = { workspace = true }
reqwest = { workspace = true, optional = true }

[features]
default = ["std"]
std = []
serde = ["dep:serde", "dep:serde_json"]
web = ["serde", "dep:axum", "dep:http"]
full = ["std", "serde", "web"]