[package]
name = "rust-ai-ide-debugger"

version = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc/rust/lang.cargo/reference/manifest.html

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
nix = { version = "0.30.1", features = ["signal", "process"] }
log = { workspace = true }
futures = { workspace = true }
rust-ai-ide-cache = { path = "../rust-ai-ide-cache" }
rust-ai-ide-errors = { path = "../rust-ai-ide-errors" }

[dev-dependencies]
shared-test-utils = { path = "../shared-test-utils" }
tokio-test = { workspace = true }
tempfile = { workspace = true }
