[package]
name = "{{crate_name}}"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[lib]
path = "src/lib.rs"

[dependencies]
# Inherit common dependencies from workspace
{{#each workspace_dependencies}}
{{this}} = { workspace = true }{{#if (eq this "tokio") }}, features = ["full"]{{/if}}
{{/each}}

[dev-dependencies]
# Test utilities
anyhow = { workspace = true }
tempfile = { workspace = true }
{{#if (eq crate_type "bin") }}

[[bin]]
name = "{{crate_name}}"
path = "src/main.rs"
{{/if}}
