[package]
name = "rust-ai-ide-shared-services"
version = { workspace = true }
edition = { workspace = true }
publish = { workspace = true }

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
uuid = { workspace = true }
async-trait = { workspace = true }
dashmap = { workspace = true }

# LSP and services
lsp-types = { workspace = true }
lsp-server = { workspace = true }
tower-lsp = { workspace = true }

# AI and request handling
reqwest = { workspace = true }

# Performance
moka = { workspace = true }
lru = { workspace = true }

# Internal dependencies
rust-ai-ide-common = { path = "../rust-ai-ide-common" }

# Concurrency
futures = { workspace = true }
rayon = { workspace = true }