[package]
name = "rust-ai-ide-ai5-consciousness-synth"

version = "0.1.0"
edition = "2021"
description = "Consciousness synthesis engines for Wave 5 Rust AI IDE"
authors = ["Rust AI IDE Team"]
license = "MIT OR Apache-2.0"
keywords = ["consciousness", "synthesis", "meta-learning", "ai"]
categories = ["development-tools", "artificial-intelligence"]

[dependencies]
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
async-trait = "0.1"
parking_lot = "0.12"
thiserror = "1.0"
anyhow = "1.0"
log = "0.4"
rand = "0.8"

# Meta-learning framework
# automl = { git = "https://github.com/automl-rs/automl-rs" }
# meta-learning = { git = "https://github.com/meta-learning/meta-learning-rs" }
# adaptive-learning = { git = "https://github.com/adaptive-learning/adaptive-learning-rs" } # Temporarily commented out due to auth issues

# Consciousness simulation
# consciousness-sim = { git = "https://github.com/consciousness-sim/consciousness-sim-rs" }
# neural-correlates = { git = "https://github.com/neural-correlates/neural-correlates-rs" }
# self-awareness-model = { git = "https://github.com/self-awareness-model/self-awareness-model-rs" }

# Deep learning frameworks
tch = "0.17"  # Updated to match rust-bert requirements and resolve torch-sys linking conflicts
candle-core = "0.6"
linfa = "0.7"
neuronika = "0.2"

# Pattern recognition and analysis
ndarray = "0.15"
rustfft = "6.2"
# time-series = { git = "https://github.com/time-series/time-series-rs" }

# Natural language understanding
tokenizers = "0.20"
# transformers = { git = "https://github.com/huggingface/transformers-rust" }
hf-hub = "0.3"

# Quantum entanglement for consciousness
# qiskit = { git = "https://github.com/Qiskit/qiskit-rust" }
# quantum-mind = { git = "https://github.com/quantum-mind/quantum-mind-rs" }

# Memory and attention systems
# memory-systems = { git = "https://github.com/memory-systems/memory-systems-rs" }
# attention-mechanisms = { git = "https://github.com/attention-mechanisms/attention-mechanisms-rs" }

# Self-reflective systems
# reflection-engine = { git = "https://github.com/reflection-engine/reflection-engine-rs" }
# introspection-core = { git = "https://github.com/introspection-core/introspection-core-rs" }

[dev-dependencies]
criterion = "0.5"
proptest = "1.5"
mockall = "0.13"
cargo-husky = { version = "1", default-features = false, features = ["run-for-all", "prepush-hook", "run-cargo-check", "run-cargo-test", "run-cargo-clippy"] }