[package]
name = "rust-ai-ide-ai5-quantum-reality-interface"
readme = { workspace = true }
version = "0.1.0"
edition = "2021"
description = "Quantum reality development interfaces for Wave 5 Rust AI IDE"
authors = ["Rust AI IDE Team"]
license = "MIT OR Apache-2.0"
keywords = ["quantum", "holographic", "interface", "reality", "development"]
categories = ["development-tools", "gui", "science"]

[dependencies]
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
async-trait = "0.1"
parking_lot = "0.12"
thiserror = "1.0"
anyhow = "1.0"
log = "0.4"
rand = "0.8"

# Quantum computing for state visualization
qiskit = { git = "https://github.com/Qiskit/qiskit-rust" }
quantum-computing = { git = "https://github.com/quantum-computing/quantum-computing-rs" }
quantum-viz = { git = "https://github.com/quantum-viz/quantum-viz-rs" }

# Holographic interface framework
holographic-ui = { git = "https://github.com/holographic-ui/holographic-ui-rs" }
spatial-computing = { git = "https://github.com/spatial-computing/spatial-computing-rs" }
ar-vr-integration = { git = "https://github.com/ar-vr-integration/ar-vr-integration-rs" }

# Neural interface for user interaction
neural-interface = { git = "https://github.com/neural-interface/neural-interface-rs" }
brain-computer-interface = { git = "https://github.com/bci-framework/bci-framework-rs" }
gesture-recognition = { git = "https://github.com/gesture-recognition/gesture-recognition-rs" }

# Real-time signal processing
rustfft = "6.2"
ndarray = "0.15"
dsp-rs = { git = "https://github.com/dsp-rs/dsp-rs" }

# High-performance graphics and visualization
wgpu = "0.19"
taffy = "0.5"
vello = { git = "https://github.com/linebender/vello" }

# Multi-modal interaction
voice-interaction = { git = "https://github.com/voice-interaction/voice-interaction-rs" }
touch-haptics = { git = "https://github.com/touch-haptics/touch-haptics-rs" }
eye-tracking = { git = "https://github.com/eye-tracking/eye-tracking-rs" }

# Quantum state management
superposition-engine = { git = "https://github.com/superposition-engine/superposition-engine-rs" }
entanglement-manager = { git = "https://github.com/entanglement-manager/entanglement-manager-rs" }
quantum-state-visualizer = { git = "https://github.com/quantum-state-visualizer/quantum-state-visualizer-rs" }

# Spatial audio for 3D interfaces
spatial-audio = { git = "https://github.com/spatial-audio/spatial-audio-rs" }
sonic-feedback = { git = "https://github.com/sonic-feedback/sonic-feedback-rs" }

[dev-dependencies]
criterion = "0.5"
proptest = "1.5"
mockall = "0.13"
cargo-husky = { version = "1", default-features = false, features = ["run-for-all", "prepush-hook", "run-cargo-check", "run-cargo-test", "run-cargo-clippy"] }