[package]
name = "rust-ai-ide-config"
readme = { workspace = true }
version = "0.1.0"
edition = "2021"
description = "Unified Security-First Configuration System for Rust AI IDE"
authors = ["Rust AI IDE Team"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/your-org/rust-ai-ide"

[dependencies]
# Unified error handling
rust-ai-ide-errors = { path = "../rust-ai-ide-errors", features = ["serde"] }
# Unified caching
rust-ai-ide-cache = { path = "../rust-ai-ide-cache" }
# Security utilities
# Common utilities
rust-ai-ide-common = { path = "../rust-ai-ide-common" }
rust-ai-ide-types = { path = "../rust-ai-ide-types" }

# Core dependencies
async-trait = "0.1"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
serde_yaml = "0.9"
toml = "0.8"

# Async runtime
tokio = { version = "1.0", features = ["full"] }

# Security & crypto
rustls = "0.23.0"
rustls-pemfile = "2.0.0"
aes-gcm = "0.10"
base64 = "0.22"
sha2 = { workspace = true }
rand = { workspace = true, features = ["std_rng"] }

# File watching for hot reload
notify = "6.1"

# Regex for validation
regex = "1.10"

# Time handling
chrono = { version = "0.4", features = ["serde"] }

# Path manipulation
walkdir = "2.5"

# Logging
tracing = "0.1"
futures = { workspace = true }
semver = { workspace = true }
dirs = "6.0.0"
anyhow = { workspace = true }

[dev-dependencies]
tempfile = "3.10"
mockall = "0.12"
