[package]
name = "rust-ai-ide-cloud-feature-flags"
readme = { workspace = true }
version = { workspace = true }
edition = { workspace = true }

[dependencies]
tokio = { workspace = true, features = ["full"] }
async-trait = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
once_cell = { workspace = true }
dashmap = { workspace = true }
tokio-util = { workspace = true }
k8s-openapi = { version = "0.20", features = ["v1_25"] }
futures = "0.3"

# Workspace dependencies
rust-ai-ide-types = { path = "../rust-ai-ide-types" }
rust-ai-ide-common = { path = "../rust-ai-ide-common" }

[dev-dependencies]
tokio-test = { workspace = true }
tempfile = { workspace = true }