[package]
name = "rust-ai-ide-ai5-meta-consciousness"

version = "0.1.0"
edition = "2021"
description = "Meta-consciousness development frameworks for Wave 5 Rust AI IDE"
authors = ["Rust AI IDE Team"]
license = "MIT OR Apache-2.0"
keywords = ["meta-consciousness", "development", "frameworks", " cognition"]
categories = ["development-tools", "artificial-intelligence"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
anyhow = "1.0"
thiserror = "1.0"
log = "0.4"