[package]
name = "rust-ai-ide-core-ai"
readme = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
description = "AI abstractions, analysis interfaces, and AI provider integrations for Rust AI IDE"
license = { workspace = true }
rust-version = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }

[dependencies]
# Base fundamentals crate
rust-ai-ide-core-fundamentals = { path = "../rust-ai-ide-core-fundamentals" }

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }

# ID generation
uuid = { workspace = true }

# Time handling
chrono = { workspace = true }

# Async trait for analysis
async-trait = { workspace = true }

[features]
default = ["std"]
std = []

# Extended features
async = []
full = ["std", "async"]