[package]
name = "rust-ai-ide-ai5-consciousness-paradigm"
version = "0.1.0"
edition = "2021"
description = "Consciousness-native programming paradigms for Wave 5 Rust AI IDE"
authors = ["Rust AI IDE Team"]
license = "MIT OR Apache-2.0"
keywords = ["consciousness", "programming", "paradigm", "neural"]
categories = ["development-tools", "compilers"]

[dependencies]
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
syn = { version = "2.0", features = ["full", "visit"] }
quote = "1.0"
proc-macro2 = "1.0"
petgraph = "0.6"
anyhow = "1.0"
thiserror = "1.0"
log = "0.4"

[dev-dependencies]
criterion = "0.5"
cargo-husky = { version = "1", default-features = false, features = ["run-for-all", "run-cargo-check", "run-cargo-test", "run-cargo-clippy"] }