[package]
name = "rust-ai-ide-common"
version = { workspace = true }
edition = { workspace = true }
publish = { workspace = true }

[dependencies]
# Workspace dependencies
anyhow = { workspace = true }
env_logger = { workspace = true, optional = true }
chrono = { workspace = true }
dashmap = { workspace = true }
dirs-next = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
notify = { workspace = true }
once_cell = { workspace = true }
rayon = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true, features = ["json", "rustls-tls"] }
semver = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
toml = { workspace = true }
uuid = { workspace = true }

# Direct dependencies with specific versions
async-trait = { workspace = true }
jsonschema = { version = "0.33.0", optional = true }
tracing = { version = "0.1.41", features = ["log"] }
tracing-subscriber = { workspace = true }

# Internal crates
paste = "1.0"  # Required for macro token concatenation
rust-ai-ide-errors = { workspace = true }

[features]
json_schema = ["jsonschema"]
test-utils = ["env_logger"]
tauri = []
tauri-integrated = []
validation = []
macros = []

[lints.rust]
# Enhanced linting for duplication prevention
pointer_structural_match = "warn"
unused_must_use = "warn"
nonstandard_style = "warn"
dead_code = "warn"
unused_variables = "warn"
unused_imports = "warn"

[[example]]
name = "logging_example"
path = "examples/logging_example.rs"
required-features = []

[[example]]
name = "default_logger"
path = "examples/default_logger.rs"
required-features = []

[lints.clippy]
# Clippy lints for code quality and duplication prevention
range_plus_one = "warn"
redundant_clone = "deny"
type_repetition_in_bounds = "deny"
struct_excessive_bools = "warn"
unnested_or_patterns = "warn"
wildcard_imports = "warn"
explicit_iter_loop = "warn"
module_name_repetitions = "warn"
extra_unused_type_parameters = "warn"
pub_use = "warn"
len_without_is_empty = "warn"
needless_continue = "warn"
semicolon_if_nothing_returned = "warn"
items_after_statements = "warn"
complexity = "warn"

[package.metadata.duplication]
# Duplication prevention configuration
check_before_commit = true
similarity_threshold = 0.85
ignore_patterns = ["test_*.rs", "*_test.rs"]
skip_checks = []