[package]
name = "rust-ai-ide-webhooks"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
# Async runtime
tokio = { workspace = true, features = ["full"] }
async-trait = { workspace = true }

# HTTP server for webhook receiving
axum = "0.8.4"
tower = "0.5.2"
tower-http = { version = "0.6.6", features = ["cors"] }

# Serialization
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

# Web framework basics
http = "1.3.1"
hyper = { version = "1.7.0", features = ["server"] }

# Authentication and security
sha2 = { workspace = true }
hex = { workspace = true }
hmac = { workspace = true }

# UUID for webhook IDs
uuid = { workspace = true, features = ["v4", "serde"] }

# Time handling
chrono = { workspace = true, features = ["serde"] }

# Configuration
thiserror = { workspace = true }

# Common core
rust-ai-ide-types = { workspace = true }
rust-ai-ide-errors = { workspace = true }

[dev-dependencies]
reqwest = { workspace = true, features = ["json"] }
tokio-test = { workspace = true }