apiVersion: v1
kind: Secret
metadata:
  name: rust-ai-ide-redis-secret
  labels:
    app: rust-ai-ide
    component: redis-cluster
type: Opaque
data:
  # Base64 encoded password (change this in production)
  password: "eGVtcGxlLXJlZGlzLXBhc3N3b3JkLTIwMjQ="  # example-redis-password-2024

---
apiVersion: v1
kind: Service
metadata:
  name: rust-ai-ide-redis-cluster
  labels:
    app: rust-ai-ide
    component: redis-cluster
spec:
  selector:
    app: rust-ai-ide
    component: redis-cluster
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  - port: 16379
    targetPort: 16379
    name: cluster
  clusterIP: None  # Headless service for Redis clustering

---
apiVersion: v1
kind: Service
metadata:
  name: rust-ai-ide-redis-service
  labels:
    app: rust-ai-ide
    component: redis-cluster
spec:
  selector:
    app: rust-ai-ide
    component: redis-cluster
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  type: ClusterIP