[build]
# Build optimization for large workspace (67 crates)
incremental = true

# Registry configuration
[registries]
crates-io = { index = "https://github.com/rust-lang/crates.io-index" }

# Build targets
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "target-cpu=native", "-C", "link-arg=-fuse-ld=lld"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"

# Net configuration for faster downloads
[net]
retry = 3