[package]
name = "shared-test-utils"
readme = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
publish = { workspace = true }

[features]
default = ["async", "serde", "tokio"]
tokio = ["tokio/full", "tokio/rt-multi-thread"]
async = ["futures", "async-trait"]
serde = ["serde/derive", "serde_json", "serde_yaml", "toml"]
database = ["rusqlite", "tokio/rt"]
mock = ["mockall"]
lsp = []
cache = []
ci = []

[dependencies]
# Core async runtime
tokio = { version = "^1.47.1", features = ["sync", "rt", "macros", "time", "rt-multi-thread"] }
tempfile = { version = "^3.21.0" }
futures = { version = "^0.3.31", optional = true }
serde = { version = "^1.0.219", features = ["derive"], optional = true }
serde_json = { version = "^1.0.143", optional = true }
thiserror = "^2.0.16"

# Async traits
async-trait = { version = "0.1.74", optional = true }

# For YAML and TOML support
serde_yaml = { version = "0.9", optional = true }
toml = { version = "0.9.5", optional = true, features = ["parse"] }

# For random data generation and templating
rand = "^0.9.0"
handlebars = "6.3.2"

# Database testing support
rusqlite = { workspace = true, optional = true }

# Mock framework
mockall = { version = "^0.13.0", optional = true }

# Additional utilities
regex = "^1.10.0"
uuid = { version = "^1.0", features = ["v4"] }
chrono = { version = "^0.4", features = ["serde"] }
num_cpus = "^1.16.0"

[dev-dependencies]
proptest = "^1.7.0"
tempfile = "^3.21.0"
assert_matches = "1.5"
criterion = { version = "0.7.0", features = ["html_reports"] }
cargo-tarpaulin = { version = "0.32.8", default-features = false }
tokio-test = "0.4"
mockito = "1.5"

# For integration testing
reqwest = { version = "0.12", features = ["json"] }
wiremock = "0.6"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]