[package]
name = "rust-ai-ide-ai5-infinite-intelligence"
readme = { workspace = true }
version = "0.1.0"
edition = "2021"
description = "Infinite intelligence development systems for Wave 5 Rust AI IDE"
authors = ["Rust AI IDE Team"]
license = "MIT OR Apache-2.0"
keywords = ["infinite", "intelligence", "ai", "transcending", "self-evolving"]
categories = ["development-tools", "artificial-intelligence"]

[dependencies]
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
async-trait = "0.1"
parking_lot = "0.12"
thiserror = "1.0"
anyhow = "1.0"
log = "0.4"
rand = "0.8"

# Self-evolving AI frameworks
# evolutionary-ai = { git = "https://github.com/evolutionary-ai/evolutionary-ai-rs" }
# meta-intelligence = { git = "https://github.com/meta-intelligence/meta-intelligence-rs" }
# infinite-learning = { git = "https://github.com/infinite-learning/infinite-learning-rs" }
# self-transcending-ai = { git = "https://github.com/self-transcending-ai/self-transcending-ai-rs" }

# Advanced ML frameworks
candle-core = "0.6"
linfa = "0.7"
tch = "0.13"
neuronika = "0.2"
# tract-onnx = { git = "https://github.com/sonos/tract" }

# Consciousness-powered learning
# consciousness-ml = { git = "https://github.com/consciousness-ml/consciousness-ml-rs" }
# meta-cognition-engine = { git = "https://github.com/meta-cognition-engine/meta-cognition-engine-rs" }

[dev-dependencies]
criterion = "0.5"
proptest = "1.5"
mockall = "0.13"
cargo-husky = { version = "1", default-features = false, features = ["run-for-all", "prepush-hook", "run-cargo-check", "run-cargo-test", "run-cargo-clippy"] }