[package]
name = "rust-ai-ide-collaboration"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
uuid = { workspace = true }

[lib]
name = "rust_ai_ide_collaboration"
path = "src/lib.rs"