[package]
name = "rust-ai-ide-cargo"
version = { workspace = true }
edition = { workspace = true }
description = "Cargo integration for Rust AI IDE"

[features]
default = ["tauri"]
tauri = ["dep:tauri"]

[dependencies]
# Workspace dependencies
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
toml = { workspace = true }
walkdir = { workspace = true }
tempfile = { workspace = true, optional = true }
chrono = { workspace = true }
uuid = { workspace = true }
futures = { workspace = true }
rayon = { workspace = true }
petgraph = { workspace = true }
semver = { workspace = true }
thiserror = { workspace = true }

# Direct dependencies with specific versions
cargo_metadata = "0.22.0"
urlencoding = "2.1.3"
url = "2.5.7"
indexmap = { version = "2.11.0", features = ["serde"] }
serde_bytes = "0.11.17"

# Internal crates
rust-ai-ide-core = { path = "../rust-ai-ide-core" }
rust-ai-ide-cache = { path = "../rust-ai-ide-cache" }

# Tauri is only used for the desktop app, not in the cargo library
tauri = { workspace = true, optional = true, features = ["test"] }
tauri-runtime = { workspace = true }

# Database
rusqlite = { workspace = true }
sysinfo = { workspace = true }

[dev-dependencies]
assert_matches = "1.5.0"
tauri-runtime-wry = { version = "2.8.1", default-features = false }
shared-test-utils = { path = "../shared-test-utils" }
tempfile = { workspace = true }
