// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/tauri-apps/gir-files)
// DO NOT EDIT

mod class;
pub use self::class::Class;

mod context;
pub use self::context::Context;

mod exception;
pub use self::exception::Exception;

mod value;
pub use self::value::Value;

mod virtual_machine;
pub use self::virtual_machine::VirtualMachine;

mod weak_value;
pub use self::weak_value::WeakValue;

mod enums;
#[cfg(feature = "v2_38")]
#[cfg_attr(docsrs, doc(cfg(feature = "v2_38")))]
pub use self::enums::TypedArrayType;
pub use self::enums::{
    CheckSyntaxMode,
    CheckSyntaxResult,
    OptionType,
};

mod flags;
pub use self::flags::ValuePropertyFlags;

pub(crate) mod traits {
    pub use super::{
        context::ContextExt,
        exception::ExceptionExt,
        value::ValueExt,
        weak_value::WeakValueExt,
    };
}
pub(crate) mod builders {
    pub use super::{
        context::ContextBuilder,
        value::ValueBuilder,
        weak_value::WeakValueBuilder,
    };
}
