[package]
name = "rust-ai-ide-wasm-components"
readme = { workspace = true }
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
default = ["console_error_panic_hook"]
console_error_panic_hook = ["dep:console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = [
  "console",
  "Window",
  "Document",
  "Element",
  "HtmlElement",
  "Node",
  "Text",
  "Performance",
  "PerformanceTiming",
  "DomRect",
  "CssStyleDeclaration",
  "EventTarget",
] }
js-sys = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6"
console_error_panic_hook = { version = "0.1", optional = true }
wee_alloc = "0.4"
rayon = "1.7"
ndarray = { version = "0.15", default-features = false }

# Workspace dependencies for shared types and utilities
rust-ai-ide-shared-types = { path = "../rust-ai-ide-shared-types", default-features = false }
rust-ai-ide-common = { path = "../rust-ai-ide-common", default-features = false }

[dependencies.parking_lot]
version = "0.12"
default-features = false

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
debug = false

[profile.dev]
opt-level = 0
debug = true
overflow-checks = true