[package]
name = "rust-ai-ide-cache"

version = "0.1.0"
edition = "2021"
description = "Unified caching infrastructure for Rust AI IDE"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
async-trait = { version = "0.1.89" }
bincode = { version = "1.0.1", optional = true }
dashmap = "6.1.0"
moka = { version = "0.12.10", default-features = false, features = ["future"] }
chrono = { version = "0.4.41", default-features = false, features = ["serde"] }
redis = { version = "0.25.4", default-features = false, features = ["tokio-comp"], optional = true }
bb8 = { version = "0.8.5", optional = true }
bb8-redis = { version = "0.15.0", optional = true }
serde = { version = "1.0.219", default-features = false, features = ["derive"] }
serde_json = "1.0.143"
sled = { version = "0.34.7", optional = true }
tokio = { version = "1.47.1", default-features = false, features = ["sync", "rt", "macros", "time"] }
tracing = "0.1"
sha256 = "1.6.0"
rust-ai-ide-errors = { path = "../rust-ai-ide-errors" }
rayon = "1.8"          # For parallel cache operations
uuid = { version = "1.0", features = ["v4", "serde"] }
zstd = { version = "0.13", optional = true }  # For compression support
tempfile.workspace = true

[features]
persistent = ["sled"]
compression = ["bincode", "zstd"]
redis-backend = ["redis", "bb8", "bb8-redis"]
redis-cluster = ["redis", "bb8", "bb8-redis", "redis/cluster"]

[dev-dependencies]
criterion = "0.7.0"
tokio-test = "0.4.4"

[[bench]]
name = "cache_benchmark"

harness = false
