[package]
name = "rust-ai-ide-cache"
readme = { workspace = true }
version = "0.1.0"
edition = "2021"
description = "Unified caching infrastructure for Rust AI IDE"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
async-trait = { version = "0.1.89" }
bincode = { version = "1.0.1", optional = true }
dashmap = "6.1.0"
chrono = { version = "0.4.41", default-features = false, features = ["serde"] }
redis = { version = "0.25.4", default-features = false, features = ["tokio-comp"], optional = true }
serde = { version = "1.0.219", default-features = false, features = ["derive"] }
serde_json = "1.0.143"
sled = { version = "0.34.7", optional = true }
tokio = { version = "1.47.1", default-features = false, features = ["sync", "rt", "macros"] }
tracing = "0.1"
sha256 = "1.6.0"
rust-ai-ide-errors = { path = "../rust-ai-ide-errors" }
rayon = "1.8"          # For parallel cache operations

[features]
persistent = ["sled"]
compression = ["bincode"]
redis-backend = ["redis"]
redis-cluster = ["redis", "redis/cluster"]

[dev-dependencies]
criterion = "0.7.0"
tokio-test = "0.4.4"

[[bench]]
name = "cache_benchmark"
readme = { workspace = true }
harness = false