[book]
title = "Rust AI IDE Documentation"
description = "Comprehensive documentation for Rust AI IDE"
authors = ["Rust AI IDE Team"]
language = "en"
multilingual = false
src = "src"

[output.html]
default-theme = "rust"
preferred-dark-theme = "navy"

[output.html.fold]
enable = true
level = 2

[output.html.redirect]
"/" = "overview/README.html"

[output.html.search]
limit-results = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 2
copy-js = true
