[package]
name = "rust-ai-ide-performance"
readme = { workspace = true }
version = "0.1.0"
edition = "2021"

[dependencies]
rust-ai-ide-core = { path = "../rust-ai-ide-core" }
rust-ai-ide-types = { path = "../rust-ai-ide-types" }
rust-ai-ide-shared-types = { path = "../rust-ai-ide-shared-types" }
rust-ai-ide-simd = { path = "../rust-ai-ide-simd" }
rust-ai-ide-cargo = { path = "../rust-ai-ide-cargo" }
cargo_metadata = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
rayon = { workspace = true }
num_cpus = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
rand = { workspace = true }
walkdir = { workspace = true }
futures = { workspace = true }
moka = { workspace = true }
warp = "0.3"

[lib]
name = "rust_ai_ide_performance"
readme = { workspace = true }
path = "src/lib.rs"