[package]
name = "rust-ai-ide-performance"
version = "0.1.0"
edition = "2021"

[dependencies]
rust-ai-ide-core = { path = "../rust-ai-ide-core" }
rust-ai-ide-types = { path = "../rust-ai-ide-types" }
rust-ai-ide-shared-types = { path = "../rust-ai-ide-shared-types" }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
rayon = { workspace = true }
num_cpus = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }

[lib]
name = "rust_ai_ide_performance"
path = "src/lib.rs"