[package]
name = "rust-ai-ide-semantic-search"
readme = { workspace = true }
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "^1.47", default-features = false, features = ["full"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
async-trait = "^0.1"
parking_lot = { version = "^0.12", default-features = false, features = [] }
regex = "^1.11"
rayon = "^1.7"
walkdir = "^2.5"
ignore = { version = "^0.4.23" }
tree-sitter = "^0.25.9"
tree-sitter-rust = "^0.24.0"
tree-sitter-javascript = "^0.25.0"
tree-sitter-typescript = "^0.23.2"
tree-sitter-python = "^0.23.6"
tree-sitter-go = "^0.25.0"
tree-sitter-java = "^0.23.5"
tree-sitter-cpp = "^0.23.4"
thiserror = "^1.0"
sha2 = "^0.10"
uuid = { version = "^1.18", features = ["v4"] }

# Workspace dependencies
rust-ai-ide-shared-types = { path = "../../crates/rust-ai-ide-shared-types", default-features = false }
rust-ai-ide-vector-database = { path = "../rust-ai-ide-vector-database", default-features = false }
rust-ai-ide-onnx-runtime = { path = "../rust-ai-ide-onnx-runtime", default-features = false }
rust-ai-ide-common = { path = "../../crates/rust-ai-ide-common", default-features = false }
rust-ai-ide-security = { path = "../../crates/rust-ai-ide-security", default-features = false }
rust-ai-ide-cache = { path = "../../crates/rust-ai-ide-cache", default-features = false }
rust-ai-ide-errors = { path = "../../crates/rust-ai-ide-errors", default-features = false }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1