[package]
name = "rust-ai-ide-incremental-parsing"
version = "0.1.0"
edition = "2021"
rust-version = "1.91.0"
description = "Dedicated crate for incremental parsing with tree-sitter integration, AST diffing algorithms, and incremental parse tree updates"
license = "MIT OR Apache-2.0"

[dependencies]
tree-sitter = "0.20"
tokio = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true, features = ["derive"] }
rust-ai-ide-shared-types = { path = "../shared-types" }
rust-ai-ide-cache = { path = "../cache" }

[dependencies.tree-sitter-rust]
version = "0.20"
optional = true

[dependencies.tree-sitter-typescript]
version = "0.20"
optional = true

[dependencies.tree-sitter-python]
version = "0.20"
optional = true

[dependencies.tree-sitter-java]
version = "0.20"
optional = true

[dependencies.tree-sitter-cpp]
version = "0.20"
optional = true

[features]
default = []
rust = ["tree-sitter-rust"]
typescript = ["tree-sitter-typescript"]
python = ["tree-sitter-python"]
java = ["tree-sitter-java"]
cpp = ["tree-sitter-cpp"]
multilang = ["rust", "typescript", "python", "java", "cpp"]